import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-municipal-utility-franchise-fee-audit",
  "engine": "recovery",
  "title": "Municipal Utility Franchise Fee Audit",
  "shortTitle": "Municipal Utility Franchise Fee Audit",
  "tagline": "Reconstruct utility gross receipts and recover underpaid municipal franchise fees across territories and customer classes.",
  "industry": "Municipal Revenue Assurance",
  "buyer": "Cities, counties, and public finance departments",
  "uiPort": 4692,
  "apiPort": 5692,
  "accent": "#0f766e",
  "currency": "USD",
  "primaryOutcome": "Municipal Utility Franchise Fee Audit converted into governed, evidence-backed financial outcomes",
  "valueNarrative": "Connect franchise agreements, service addresses, customer classes, gross receipts, exclusions, rates, returns, payments, and audits in one accountable workflow. Reconstruct utility gross receipts and recover underpaid municipal franchise fees across territories and customer classes.",
  "calculation": {
    "actualKey": "receivedAmount",
    "expectedKey": "entitledAmount",
    "actualLabel": "Received or Recognized Amount",
    "expectedLabel": "Contract or Rule-Supported Entitlement",
    "varianceLabel": "Unrecovered supported value",
    "direction": "expected-minus-actual",
    "finding": "Municipal Utility Franchise Fee Audit evidence indicates a measurable financial exception.",
    "actions": [
      "Validate the effective agreement, eligibility rules, and accountable parties",
      "Reconcile transaction-level operational and financial evidence",
      "Prepare the correction, recovery, or compliance package",
      "Track counterparty response, approval, cash, and preventive control closure"
    ]
  }
},[
feature("franchise-agreement-library","MUF01","Franchise agreement library","Execute franchise agreement library using franchise agreements, service addresses, customer classes, gross receipts, exclusions, rates, returns, payments, and audits.","Produce a governed franchise agreement library decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Utility / Franchise Territory","text","Utility / Franchise Territory · Standard Case"],["caseReference","Franchise agreement library Reference","text","MUF01-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1181250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1429313],["domainDriver","Utility Type","select","Electric",["Electric","Gas","Cable telecom"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Franchise agreement library case","Territory boundary mapping case","Service address matching case","Customer class mapping case","Gross receipt ingestion case"]}),
feature("territory-boundary-mapping","MUF02","Territory boundary mapping","Execute territory boundary mapping using franchise agreements, service addresses, customer classes, gross receipts, exclusions, rates, returns, payments, and audits.","Produce a governed territory boundary mapping decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Utility / Franchise Territory","text","Utility / Franchise Territory · Standard Case"],["caseReference","Territory boundary mapping Reference","text","MUF02-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1181250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1429313],["domainDriver","Utility Type","select","Electric",["Electric","Gas","Cable telecom"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Franchise agreement library case","Territory boundary mapping case","Service address matching case","Customer class mapping case","Gross receipt ingestion case"]}),
feature("service-address-matching","MUF03","Service address matching","Execute service address matching using franchise agreements, service addresses, customer classes, gross receipts, exclusions, rates, returns, payments, and audits.","Produce a governed service address matching decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Utility / Franchise Territory","text","Utility / Franchise Territory · Standard Case"],["caseReference","Service address matching Reference","text","MUF03-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1181250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1429313],["domainDriver","Utility Type","select","Electric",["Electric","Gas","Cable telecom"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Franchise agreement library case","Territory boundary mapping case","Service address matching case","Customer class mapping case","Gross receipt ingestion case"]}),
feature("customer-class-mapping","MUF04","Customer class mapping","Execute customer class mapping using franchise agreements, service addresses, customer classes, gross receipts, exclusions, rates, returns, payments, and audits.","Produce a governed customer class mapping decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Utility / Franchise Territory","text","Utility / Franchise Territory · Standard Case"],["caseReference","Customer class mapping Reference","text","MUF04-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1181250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1429313],["domainDriver","Utility Type","select","Electric",["Electric","Gas","Cable telecom"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Franchise agreement library case","Territory boundary mapping case","Service address matching case","Customer class mapping case","Gross receipt ingestion case"]}),
feature("gross-receipt-ingestion","MUF05","Gross receipt ingestion","Execute gross receipt ingestion using franchise agreements, service addresses, customer classes, gross receipts, exclusions, rates, returns, payments, and audits.","Produce a governed gross receipt ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Utility / Franchise Territory","text","Utility / Franchise Territory · Standard Case"],["caseReference","Gross receipt ingestion Reference","text","MUF05-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1181250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1429313],["domainDriver","Utility Type","select","Electric",["Electric","Gas","Cable telecom"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Franchise agreement library case","Territory boundary mapping case","Service address matching case","Customer class mapping case","Gross receipt ingestion case"]}),
feature("excluded-revenue-validation","MUF06","Excluded revenue validation","Execute excluded revenue validation using franchise agreements, service addresses, customer classes, gross receipts, exclusions, rates, returns, payments, and audits.","Produce a governed excluded revenue validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Utility / Franchise Territory","text","Utility / Franchise Territory · Standard Case"],["caseReference","Excluded revenue validation Reference","text","MUF06-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1181250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1429313],["domainDriver","Utility Type","select","Electric",["Electric","Gas","Cable telecom"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Franchise agreement library case","Territory boundary mapping case","Service address matching case","Customer class mapping case","Gross receipt ingestion case"]}),
feature("rate-tier-calculation","MUF07","Rate tier calculation","Execute rate tier calculation using franchise agreements, service addresses, customer classes, gross receipts, exclusions, rates, returns, payments, and audits.","Produce a governed rate tier calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Utility / Franchise Territory","text","Utility / Franchise Territory · Standard Case"],["caseReference","Rate tier calculation Reference","text","MUF07-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1181250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1429313],["domainDriver","Utility Type","select","Electric",["Electric","Gas","Cable telecom"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Franchise agreement library case","Territory boundary mapping case","Service address matching case","Customer class mapping case","Gross receipt ingestion case"]}),
feature("bad-debt-treatment","MUF08","Bad debt treatment","Execute bad debt treatment using franchise agreements, service addresses, customer classes, gross receipts, exclusions, rates, returns, payments, and audits.","Produce a governed bad debt treatment decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Utility / Franchise Territory","text","Utility / Franchise Territory · Standard Case"],["caseReference","Bad debt treatment Reference","text","MUF08-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1181250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1429313],["domainDriver","Utility Type","select","Electric",["Electric","Gas","Cable telecom"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Franchise agreement library case","Territory boundary mapping case","Service address matching case","Customer class mapping case","Gross receipt ingestion case"]}),
feature("affiliate-revenue-review","MUF09","Affiliate revenue review","Execute affiliate revenue review using franchise agreements, service addresses, customer classes, gross receipts, exclusions, rates, returns, payments, and audits.","Produce a governed affiliate revenue review decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Utility / Franchise Territory","text","Utility / Franchise Territory · Standard Case"],["caseReference","Affiliate revenue review Reference","text","MUF09-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1181250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1429313],["domainDriver","Utility Type","select","Electric",["Electric","Gas","Cable telecom"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Franchise agreement library case","Territory boundary mapping case","Service address matching case","Customer class mapping case","Gross receipt ingestion case"]}),
feature("return-period-reconciliation","MUF10","Return period reconciliation","Execute return period reconciliation using franchise agreements, service addresses, customer classes, gross receipts, exclusions, rates, returns, payments, and audits.","Produce a governed return period reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Utility / Franchise Territory","text","Utility / Franchise Territory · Standard Case"],["caseReference","Return period reconciliation Reference","text","MUF10-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1181250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1429313],["domainDriver","Utility Type","select","Electric",["Electric","Gas","Cable telecom"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Franchise agreement library case","Territory boundary mapping case","Service address matching case","Customer class mapping case","Gross receipt ingestion case"]}),
feature("underpayment-calculation","MUF11","Underpayment calculation","Execute underpayment calculation using franchise agreements, service addresses, customer classes, gross receipts, exclusions, rates, returns, payments, and audits.","Produce a governed underpayment calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Utility / Franchise Territory","text","Utility / Franchise Territory · Standard Case"],["caseReference","Underpayment calculation Reference","text","MUF11-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1181250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1429313],["domainDriver","Utility Type","select","Electric",["Electric","Gas","Cable telecom"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Franchise agreement library case","Territory boundary mapping case","Service address matching case","Customer class mapping case","Gross receipt ingestion case"]}),
feature("utility-audit-request","MUF12","Utility audit request","Execute utility audit request using franchise agreements, service addresses, customer classes, gross receipts, exclusions, rates, returns, payments, and audits.","Produce a governed utility audit request decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Utility / Franchise Territory","text","Utility / Franchise Territory · Standard Case"],["caseReference","Utility audit request Reference","text","MUF12-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1181250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1429313],["domainDriver","Utility Type","select","Electric",["Electric","Gas","Cable telecom"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Franchise agreement library case","Territory boundary mapping case","Service address matching case","Customer class mapping case","Gross receipt ingestion case"]}),
feature("assessment-notice-workflow","MUF13","Assessment notice workflow","Execute assessment notice workflow using franchise agreements, service addresses, customer classes, gross receipts, exclusions, rates, returns, payments, and audits.","Produce a governed assessment notice workflow decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Utility / Franchise Territory","text","Utility / Franchise Territory · Standard Case"],["caseReference","Assessment notice workflow Reference","text","MUF13-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1181250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1429313],["domainDriver","Utility Type","select","Electric",["Electric","Gas","Cable telecom"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Franchise agreement library case","Territory boundary mapping case","Service address matching case","Customer class mapping case","Gross receipt ingestion case"]}),
feature("cash-collection-tracking","MUF14","Cash collection tracking","Execute cash collection tracking using franchise agreements, service addresses, customer classes, gross receipts, exclusions, rates, returns, payments, and audits.","Produce a governed cash collection tracking decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Utility / Franchise Territory","text","Utility / Franchise Territory · Standard Case"],["caseReference","Cash collection tracking Reference","text","MUF14-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1181250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1429313],["domainDriver","Utility Type","select","Electric",["Electric","Gas","Cable telecom"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Franchise agreement library case","Territory boundary mapping case","Service address matching case","Customer class mapping case","Gross receipt ingestion case"]}),
feature("territory-utility-analytics","MUF15","Territory utility analytics","Execute territory utility analytics using franchise agreements, service addresses, customer classes, gross receipts, exclusions, rates, returns, payments, and audits.","Produce a governed territory utility analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Utility / Franchise Territory","text","Utility / Franchise Territory · Standard Case"],["caseReference","Territory utility analytics Reference","text","MUF15-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1181250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1429313],["domainDriver","Utility Type","select","Electric",["Electric","Gas","Cable telecom"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Franchise agreement library case","Territory boundary mapping case","Service address matching case","Customer class mapping case","Gross receipt ingestion case"]})
]);
